
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycxvvcofpcavdogtymjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljeHZ2Y29mcGNhdmRvZ3R5bWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTkzMTksImV4cCI6MjA2MDM5NTMxOX0.ICccDDHw6oMaoHGgJYe7wg22QqkLWIHpQ8dhYNTLOGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
